# Generated by Django 4.2 on 2024-02-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='interface',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT')], max_length=255, null=True),
        ),
    ]
