# Generated by Django 4.2 on 2024-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='interface',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'DEFAULT'), ('PROFILE', 'PROFILE')], max_length=255, null=True),
        ),
    ]
